server:
  port: 8083

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    reactor.netty: TRACE

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENTID}
            client-secret: ${GOOGLE_CLIENTSECRET}
            scope: openid,profile,email
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
  cloud:
    gateway:
      routes:
        - id: timeslot-service
          uri: http://${TIMESLOT_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/timeslot
            - Method=GET
          filters:
            - SetPath=/api/timeslot
        - id: timeslot-service
          uri: http://${TIMESLOT_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/timeslot
            - Method=POST
          filters:
            - SetPath=/api/timeslot
        - id: timeslot-service-delete
          uri: http://${TIMESLOT_SERVICE_BASEURL:localhost:8080}
          predicates:
            - Path=/timeslot
            - Method=DELETE
          filters:
            - SetPath=/api/timeslot

        - id: stage-service
          uri: http://${STAGE_SERVICE_BASEURL:localhost:8082}
          predicates:
            - Path=/stage
            - Method=POST
          filters:
            - SetPath=/api/stage
        - id: stage-service
          uri: http://${STAGE_SERVICE_BASEURL:localhost:8082}
          predicates:
            - Path=/stage
            - Method=GET
          filters:
            - SetPath=/api/stage
        - id: stage-service-all
          uri: http://${STAGE_SERVICE_BASEURL:localhost:8082}
          predicates:
            - Path=/stage/all
            - Method=GET
          filters:
            - SetPath=/api/stage/all
        - id: stage-service-delete
          uri: http://${STAGE_SERVICE_BASEURL:localhost:8082}
          predicates:
            - Path=/stage
            - Method=DELETE
          filters:
            - SetPath=/api/stage

        - id: artist-service
          uri: http://${ARTIST_SERVICE_BASEURL:localhost:8080}
          predicates:
            - Path=/artist
            - Method=GET
          filters:
            - SetPath=/api/artist
        - id: artist-service-all
          uri: http://${ARTIST_SERVICE_BASEURL:localhost:8080}
          predicates:
            - Path=/artist/all
            - Method=GET
          filters:
            - SetPath=/api/artist/all
        - id: artist-service-delete
          uri: http://${ARTIST_SERVICE_BASEURL:localhost:8080}
          predicates:
            - Path=/artist
            - Method=DELETE
          filters:
            - SetPath=/api/artist